name: inspec-azure-compliance-check
title: InSpec Azure Checker Profile
maintainer: ambilykk
copyright: Apache MIT
copyright_email: test@domain.com
license: Apache-2.0
summary: An InSpec Azure Profile Demo
version: 0.1.0
inspec_version: '>= 4.0.0'
depends:
- name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/refs/tags/v1.75.9.tar.gz

supports:
- platform: azure
